---
apiVersion: v1
kind: Pod
metadata:
  namespace: abcdesktop
  name: pyos-debug-tools 
  labels:
    abcdesktop/role: kubectl
    netpol/https: 'true'
    netpol/ldaps: 'true'
    netpol/auth: 'true'
    netpol/cifs: 'true'
    netpol/api: 'true'
    netpol/dns: 'true'
    netpol/mongodb: 'true'
    netpol/memcached: 'true'
    netpol/graylog: 'true'
spec:
    serviceAccountName: pyos-serviceaccount
    containers:
    - name : pyos-debug-tools
      imagePullPolicy: Always
      image: abcdesktopio/pyos-debug-tools:main
      env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    dnsPolicy: ClusterFirst
---
